apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "docker-registry.name" . }}
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
