apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "docker-registry.name" . }}
type: Opaque
data:
  {{- if .Values.secrets.htpasswd }}
  htpasswd: {{ .Values.secrets.htpasswd | b64enc }}
  {{- end }}
  {{- if .Values.secrets.haSharedSecret }}
  haSharedSecret: {{ .Values.secrets.haSharedSecret | b64enc | quote }}
  {{- else }}
  haSharedSecret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  proxyUsername: {{ .Values.proxy.username | default "" | b64enc | quote }}
  proxyPassword: {{ .Values.proxy.password | default "" | b64enc | quote }}
