
labels:
  app: "requester-services-dx"
  group: "dx"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "requester-services-dx"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "requester-services-dx"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/requester-services-dx/health"
  readinessProbePath: "/requester-services-dx/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"
java-debug: ""

# Additional Container Envs
env: |
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-debug" | quote }}
 
