apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pre-install-{{ template "kibana.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: pre-install-{{ template "kibana.fullname" . }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  kind: Role
  name: pre-install-{{ template "kibana.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
