apiVersion: v1
kind: ServiceAccount
metadata:
  name: pre-install-{{ template "kibana.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}
