labels:
  app: "postgres"
  group: "db"
namespace: egov

image:
  repository: "docker.io/postgres"
  tag: "9.6"
replicas: "1"
httpPort: 5432

resources: |
  requests:
    cpu: 100m
    memory: 256Mi

tracing-enabled: false

persistence:
  enabled: false
  size: "20Gi"
  storageClass: "gp2"
  accessMode: "ReadWriteOnce"

env: |
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name:  POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: POSTGRES_DB
    value: {{ default "" .Values.postgresDatabase | quote }}
extraVolumeMounts: |
  - name: postgres-volume
    mountPath: /var/lib/postgresql
extraVolumes: |
  - name: postgres-volume
  {{- if .Values.persistence.enabled }}
    persistentVolumeClaim:
      claimName: pvc-postgres
  {{- end }}

postgresDatabase: egov_ms      
