{{- with index .Values "cluster-configs" "secrets" "elasticsearch" }}
{{- if index . "password" }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index $.Values "cluster-configs" "secrets" "elasticsearch" "name" }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "elasticsearch" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "elasticsearch" "password" | b64enc | quote }}
---
{{- end }}
{{- end }}
{{- end }}
